# Generated by Django 5.1.1 on 2024-10-10 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
