# Generated by Django 5.1.1 on 2024-10-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testes', '0002_delete_yourmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbPlacas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME', models.CharField(max_length=30)),
                ('COD', models.CharField(max_length=4)),
                ('ADD_CAN', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tbTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME', models.CharField(max_length=30)),
                ('COD', models.CharField(max_length=4)),
            ],
        ),
    ]
