# Generated by Django 5.1.1 on 2024-10-11 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbTipo',
            new_name='tbTipos',
        ),
    ]
