# Generated by Django 5.1.1 on 2024-10-11 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0005_tbpropriedades'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbTestes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATA', models.TimeField(verbose_name='TIMESTAMP')),
                ('FK_PLACA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testes.tbplacas')),
            ],
        ),
    ]
