# Generated by Django 5.1.1 on 2024-10-11 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0006_tbtestes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbtestes',
            name='FK_PROPRIEDADE',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='testes.tbpropriedades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbtestes',
            name='RESULTADO',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbtestes',
            name='TIPO_TESTE',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
