# Generated by Django 5.0.3 on 2024-11-09 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0009_tboperacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbtestes',
            name='FK_OPERACAO',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testes.tboperacoes'),
            preserve_default=False,
        ),
    ]
